ALTER TABLE verification_tokens
ADD COLUMN created_at TIMESTAMP;

ALTER TABLE team_vaults
ALTER COLUMN type SET DATA TYPE VARCHAR(255);

ALTER TABLE data_blocks
ALTER COLUMN type SET DATA TYPE  VARCHAR(255);

ALTER TABLE team_vault_user
ALTER COLUMN role SET DATA TYPE VARCHAR(255)